title: Svetlozar Kostadinov
subtitle: Software Developer
desc: Personal site, CV, developer portfolio
author: Svetlozar Kostadinov
keywords: developer,programmer,android,java,kotlin,c++,cv,personal,resume,portfolio,bulgaria,sofia
attribution: "Â© 2018 Svetlozar Kostadinov. Powered by Jekyll. Hosted by GitHub. [Source code](https://github.com/sevar83/sevar83.github.io)"
permalink: pretty
collections:
    timeline:
        title: CV
    projects:
    movielovers:
        title: MovieLovers
    geoworld:
        title: GeoWorld
    panelhome3d:
        title: PanelHome3D
    buildware3d:
        title: Buildware3D
